server:
  port:8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/zwap-7df78
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: product-write-service
          uri: lb://product-write-service
          predicates:
            - Path=/product-write-service/**
          filters:
            - StripPrefix=1

        - id: product-read-service
          uri: lb://product-read-service
          predicates:
            - Path=/product-read-service/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka
  instance:
    prefer-ip-address: false
    hostname: ${SERVER_HOST}
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-port: 443
    non-secure-port: 80
    home-page-url: https://${SERVER_HOST}
    health-check-url: https://${SERVER_HOST}/actuator/health
    status-page-url: https://${SERVER_HOST}/actuator/info