service:
  uri:
    eureka: http://localhost:50008
    api-gateway: http://localhost:50007
    product-read: http://localhost:50009
    product-write: http://localhost:50010
    product-search: http://localhost:50011
    user: http://localhost:50012