service:
  uri:
    eureka: http://linux-077:50008
    api-gateway: http://linux-078:50007
    product-read: http://linux-079:50009
    product-write: http://linux-080:50010
    product-search: http://linux-081:50011
    user: http://linux-082:50012