EUREKA_SERVICE_URI: http://localhost:50008
API_GATEWAY_SERVICE_URI: http://localhost:50007
PRODUCT_READ_SERVICE_URI: http://localhost:50009
PRODUCT_WRITE_SERVICE_URI: http://localhost:50010
PRODUCT_SEARCH_SERVICE_URI: http://localhost:50011
USER_SERVICE_URI: http://localhost:50012
CONFIG_SERVICE_URI: http://localhost:50013