EUREKA_SERVICE_URI: http://linux-077:50008
API_GATEWAY_SERVICE_URI: http://linux-078:50007
PRODUCT_READ_SERVICE_URI: http://linux-079:50009
PRODUCT_WRITE_SERVICE_URI: http://linux-080:50010
PRODUCT_SEARCH_SERVICE_URI: http://linux-081:50011
USER_SERVICE_URI: http://linux-082:50012
CONFIG_SERVICE_URI: http://linux-075:50013