spring:
  boot:
    admin:
      context-path: /admin
  application:
    name: eureka-server
  security:
    user:
      name: jingjie
      password: xiuxiulovejingjie

server:
  port: 8761
  servlet:
    context-path: /

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

