spring:
  boot:
    admin:
      ui:
        path: /admin
  application:
    name: eureka-server
  security:
    user:
      name: jingjie
      password: xiuxiulovejingjie

server:
  port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_PEER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

