spring:
  application:
    name: eureka-server
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}

server:
  port: 8761
  servlet:
    context-path: /admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_PEER_URL:http://localhost:8761/eureka/}  # fallback if no env var

