spring:
  data:
    mongodb:
      uri: {PRODUCT_MONGODB_SERVICE_URI}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${service.uri.eureka}/eureka